---
personal_homebrew_cli:
  - ansible
  - difftastic
  - fluxcd/tap/flux
  - gh
  - glab
  - kubernetes-cli
  - opencode
  - opentofu
  - talosctl

personal_cask_packages:
  - opencode-desktop

personal_apt_packages:
  - flatpak
  - podman

personal_flatpak_packages:
  - io.podman_desktop.PodmanDesktop
