---
# vars file for base role
base_os_font_dir:
  RedHat: "/usr/local/share/fonts/nerd-fonts"
  Debian: "/usr/local/share/fonts/nerd-fonts"
  Darwin: "{{ ansible_facts.env.HOME }}/Library/Fonts"

base_font_dir: "{{ base_os_font_dir[ansible_facts.os_family] }}"

base_cli_packages:
  - ansible-lint
  - bat
  - eza
  - fzf
  - gitleaks
  - pre-commit
  - ripgrep

base_nerd_fonts:
  - JetBrainsMono
